### ISSUE TITLE
Start magmaFatProxy from command line

### ISSUE THREAD

**Issue by klausdorer** [magmaOffenburg/magmaFatProxy#2]
It would be nice if magmaFatProxy also had a start.sh script and a released jar file (with version) that can be started at command line without the need build or open in and IDE (see magmaProxy).

**Comment by hannesbraun** [comment]
This should be added with 668fd244b554e0b01fede11d443948b25eed277a.
Building magmaFatProxy is now possible with the `magmaFatProxy.xml` Ant script.
